### ISSUE TITLE
fileHistoryWalk does not return all commits

### ISSUE THREAD

**Issue by littlebee** [nodegit/nodegit#1068]
When I compare the history returned by fileHistoryWalk to git log console output, there are a lot of commits missing from the fileHistoryWalk commits.

For example, using the atom editor repo and source:

``` bash
cd /tmp
git clone https://github.com/atom/atom.git
cd atom
git log src/text-editor.coffee
```

...then, using a slightly modified examples/walk-history-for-file.js (see below) and compare.  The output from the example says there are 129 commits to text-editor.coffee but git log src/text-editor.coffee shows 481 commits to that file.

modified example (changed repo, test tile path and added count output:

``` javascript
var nodegit = require("../"),
    path = require("path"),
    historyFile = "src/text-editor.coffee",
    walker,
    historyCommits = [],
    commit,
    repo;

// This code walks the history of the master branch and prints results
// that look very similar to calling `git log` from the command line

function compileHistory(resultingArrayOfCommits) {
  var lastSha;
  if (historyCommits.length > 0) {
    lastSha = historyCommits[historyCommits.length - 1].commit.sha();
    if (
      resultingArrayOfCommits.length == 1 &&
      resultingArrayOfCommits[0].commit.sha() == lastSha
    ) {
      return;
    }
  }

  resultingArrayOfCommits.forEach(function(entry) {
    historyCommits.push(entry);
  });

  lastSha = historyCommits[historyCommits.length - 1].commit.sha();

  walker = repo.createRevWalk();
  walker.push(lastSha);
  walker.sorting(nodegit.Revwalk.SORT.TIME);

  return walker.fileHistoryWalk(historyFile, 500)
    .then(compileHistory);
}

//nodegit.Repository.open(path.resolve(__dirname, "../.git"))
nodegit.Repository.open("/tmp/atom/.git")
  .then(function(r) {
    repo = r;
    return repo.getMasterCommit();
  })
  .then(function(firstCommitOnMaster){
    // History returns an event.
    walker = repo.createRevWalk();
    walker.push(firstCommitOnMaster.sha());
    walker.sorting(nodegit.Revwalk.SORT.Time);

    return walker.fileHistoryWalk(historyFile, 500);
  })
  .then(compileHistory)
  .then(function() {
    historyCommits.forEach(function(entry) {
      commit = entry.commit;
      console.log("commit " + commit.sha());
      console.log("Author:", commit.author().name() +
        " <" + commit.author().email() + ">");
      console.log("Date:", commit.date());
      console.log("\n    " + commit.message());
    });
    console.log("\n\n" + historyCommits.length + " total commits");
  })
  .done();

```

**Comment by maxkorp** [comment]
`return walker.fileHistoryWalk(historyFile, 500);` is capping the walker at 500. I'm guessing 129 of the commits that touch that file happened within the 500 commits it's walking.

**Comment by littlebee** [comment]
oh, i see.  I wasn't sure what that did.  So does it cap out at 64K? When I change it to 10000 I get back 207 commits.  Also get 207 at 10k increments up to 100000

**Comment by maxkorp** [comment]
Hrm, not sure there. I'll try and take a look.

**Comment by johnhaley81** [comment]
@littlebee can you try using `RevWalk#fileHistoryWalk`? A quick and dirty example:

```
const revwalk = repo.createRevWalk();
revwalk.sorting(NodeGit.Revwalk.SORT.TIME);
revwalk.push(sha);

revwalk.fileHistoryWalk(fileName, 500 /* COMMITS_PER_HISTORY_PAGE */)
  .then(entries => {
    // do stuff
  });
```

**Comment by Kovensky** [comment]
`fileHistoryWalk(fileName, 500)` seems to behave like just a regular `getCommits(500)` that filters by commits that have the `fileName`, instead of returning (up to) 500 entries that involve the `fileName`.

`revwalk.fileHistoryWalk(fileName, 1)` will always result in `[]` unless the file was modified in the commit that was pushed in the `revwalk`.

This makes `fileHistoryWalk` fairly useless IMO :(

The inability to interrupt the walk in `revWalk#walk` and/or `Commit#history()#start` also makes it very hard to only look at the most recent commits of a specific file in very large repositories, but that is a different issue.

**Comment by shaunc** [comment]
@Kovensky ... good to know -- after several hours trying to figure out why `revwalk.fileHistoryWalk(fileName, 1)` was not working as expected no matter how I sorted...

But ... grumble ... is there any workaround? Do we just have to get the whole of history to ensure that we get a single commit for a file?? (I'm looking for the first commit for a file... will sorting help me?)

**Comment by Means88** [comment]
Anything going on?

**Comment by rcjsuen** [comment]
@Means88 Work in this area is happening at the moment. See #1676. I'm not sure if the API itself is changing or not though.

**Comment by Means88** [comment]
@rcjsuen I think it's just an optimization without changing the behavior. The unit test is not changed.

https://github.com/nodegit/nodegit/blob/7d277261b1e42883cf3df87710a103795a344c16/test/tests/revwalk.js#L160-L182

**Comment by implausible** [comment]
It is a change in the behavior and merge commits were indeed respected in as close to we could approximate the algorithm in git core.

**Comment by implausible** [comment]
Also for the record, fileHistoryWalk still does not return all commits; it should now have a key on the array return `reachedEndOfHistory`. The intent is that you can request 30k to 50k commits at a time until you hit the end of history (init commit). It seems that the libgit2 revwalk might be a little slower than git core, as just the revwalk alone on the linux repository takes a considerable amount of time in comparsion to standard git core. So it is advisable in large applications to design for that slow down accordingly.

**Comment by raine** [comment]
I'm puzzled how difficult it is to do `git log -- path/to/file` with this library.

As mentioned `fileHistoryWalk` is completely useless as it doesn't seem to go through all commits in the history, no matter how large number you give it.

**Comment by rcjsuen** [comment]
> I'm puzzled how difficult it is to do `git log -- path/to/file` with this library.

@raine I implemented this in the past (in 2017?). I did this by looking at the hashes of the specific item to see if a commit was relevant or not and then just kept climbing and climbing. Merge commits had some additional logic but it wasn't impossible. Things to keep in mind would be files that are added and deleted again and again so you shouldn't just stop just because you find a `null`. Another edge case would be file histories that have orphaned branches. I'm sure there are more but those are the ones that I recall thinking about and solving when I implemented such a feature.

Also, Axosoft has also implemented this for GitKraken so it's definitely doable.

**Comment by implausible** [comment]
`fileHistoryWalk` is firmly in the good enough category in NodeGit, we actively use it in GitKraken now. I think this issue remaining open is misleading as the original discussion is on an implementation that no longer exists in NodeGit. I'm going to close this issue. If there are new reports of missing commits from `fileHistoryWalk`, I'd like to see that in a new issue with repro steps.

**Comment by 0x1af2aec8f957** [comment]
```typescript
  async function getCommit(_repo: Repository | string, count?: number): Promise<Commit[]>{
        const repo: Repository = _repo instanceof Git.Repository ? _repo : await Git.Repository.open(_repo);
        const lastCommit: Commit = await repo.getHeadCommit();

        const revWalk: Revwalk = repo.createRevWalk();
        revWalk.sorting(Git.Revwalk.SORT.TIME);
        revWalk.push(lastCommit.id());

        if (typeof count === 'undefined') return revWalk.getCommitsUntil((_commit: Commit) => false);
        return revWalk.getCommits(count);
    }
```

nodegit@0.27.0
