### ISSUE TITLE
Error on opensuse

### ISSUE THREAD

**Issue by tosone** [nodegit/nodegit#961]
everything is ready look this:
```
COPY Release/nodegit.node
make: Leaving directory '/home/tosone/code/nodegit/build'
0
[nodegit@0.11.9] scripts.install success, use 5m
[nodegit@0.11.9] scripts.prepublish: "node lifecycleScripts/prepareForBuild.js"
```
but when i run test
```
tosone@tosone:~/code/nodegit> npm test

> nodegit@0.11.9 test /home/tosone/code/nodegit
> npm run lint && node --expose-gc test


> nodegit@0.11.9 lint /home/tosone/code/nodegit
> jshint lib test/tests test/utils examples lifecycleScripts

/home/tosone/.nvm/versions/node/v5.9.0/bin/node: symbol lookup error: /home/tosone/code/nodegit/build/Release/nodegit.node: undefined symbol: gcry_control
npm ERR! Test failed.  See above for more details.

```
node: 5.9
opensuse: 42.1
gcc: 4.8.5

**Comment by johnhaley81** [comment]
@tosone did you compile nodegit or did it download a prebuilt binary? I haven't seen this error before and I'm not quite sure what's causing it.

**Comment by tosone** [comment]
sure i compile it and success. no matter which linux in virtual box i use, will occur that error. but without virtual box, everything will be OK. probably this `undefined symbol: gcry_control` is occured by virtual box.

**Comment by vsukhomlinov** [comment]
It happened to me as well when I tried to build nodegit for centos_7. Build itself passes, but crashes at runtime
node: symbol lookup error: /home/aws-user/dashboard/node_modules/nodegit/build/Release/nodegit.node: undefined symbol: gcry_control

**Comment by maxkorp** [comment]
This looks like it may be related to a libssh2 version mismatch https://bbs.archlinux.org/viewtopic.php?id=123000

**Comment by vsukhomlinov** [comment]
I fixed it yesterday by installing openssl-devel. And btw, since you guys percompile your binary on some new linux distro, I have to force `BUILD_ONLY=true` before `npm install` in centos 7. You guys might want to specify all binary dependencies for Linux users.

**Comment by maxkorp** [comment]
Yeah, thats actually a build error on our side. That should all be statically linked, but something is broken there. Def related to us not linking libssh2 to our own openssl properly :(

Closing this in lieu of https://github.com/nodegit/nodegit/issues/1093

**Comment by guoyunhe** [comment]
I still have this issue on openSUSE. Have to install openssl-devel first and then install nodegit.
